apps/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', 
		views.cart_detail, 
		name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$',
		views.cart_add,
		name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$',
		views.cart_remove,
		name='cart_remove'),
]

apps/shop/urls.py
from django.conf.urls import url
from .import views 


urlpatterns = [
	url(r'^$', 
		views.product_list, 
		name='product_list'
	),
	url(r'^(?P<category_slug>[-\w]+)/$',
		views.product_list,
		name='product_list_by_category'
	),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
		views.product_detail,
		name='product_detail'
	),
]

oneeleven/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^caronte/', admin.site.urls),
    url(r'^polls/', include('apps.polls.urls', namespace='polls')),
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^orders/', include('apps.orders.urls', namespace='orders')),
    url(r'^modal/', include('apps.modal.urls', namespace='modal')),
    url(r'^', include('apps.shop.urls', namespace='shop')),
]

# configuration for serve media files in local
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/shop/models.py
from django.core.urlresolvers import reverse
from django.db import models


class Category(models.Model):
	name = models.CharField(
		max_length=200,
		db_index=True
	)
	slug = models.SlugField(
		max_length=200,
		db_index=True,
		unique=True
	)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse(	
			'shop:product_list_by_category',
			args=[self.slug]
		)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'


class Product(models.Model):
	category = models.ForeignKey(
		Category,
		related_name='products'
	)
	name = models.CharField(
		max_length=200, 
		db_index=True
	)
	slug = models.SlugField(
		max_length=200, 
		db_index=True
	)
	image = models.ImageField(
		upload_to='products/%Y/%m/%d',
		blank=True
	)
	description = models.TextField(blank=True)
	price = models.DecimalField(
		max_digits=10, 
		decimal_places=2
	)
	stock = models.PositiveIntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse(
			'shop:product_detail',
			args=[self.id, self.slug]
		)

	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)

apps/shop/views.py
from django.shortcuts import (
	render,
	get_object_or_404,
)
from .models import (
	Category,
	Product,
)
from apps.cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)

	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category)

	return render(
		request,
		'shop/product/list.html',
		{
			'category': category,
			'categories': categories,
			'products': products,
		}
	)


def product_detail(request, id, slug):
	product = get_object_or_404(
		Product,
		id=id,
		slug=slug,
		available=True
	)
	cart_product_form = CartAddProductForm()
	return render(
		request,
		'shop/product/detail.html',
		{ 
			'product': product,
			'cart_product_form': cart_product_form,
		}
	)

apps/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>{% block title %}My shop{% endblock %}</title>
		<link href="{% static "css/base.css" %}" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
	</head>
<body>
	<div id="header">
		<a href="/" class="logo">My shop</a>
	</div>
	<div id="subheader">
<div class="cart">
	{% with total_items=cart|length %}
		{% if total_items > 0 %}
			Your cart:
			<a href="{% url 'cart:cart_detail' %}">
				{{ total_items }} item{{ total_items|pluralize }},
				${{ cart.get_total_price }}
			</a>
		{% else %}
			Your cart is empty.
		{% endif %}
	{% endwith %}
</div>
	</div>
	<div id="content">
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>