apps/polls/urls.py
from django.conf.urls import url
from .views import PollListView, PollDetailView

urlpatterns = [
    url(r'^list/$', PollListView.as_view(), name="list"),
    url(r'^detail/(?P<pk>[0-9a-f-]+)$', PollDetailView.as_view(), name="detail"),
]

oneeleven/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^caronte/', admin.site.urls),
    url(r'^polls/', include('apps.polls.urls', namespace='polls')),
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^orders/', include('apps.orders.urls', namespace='orders')),
    url(r'^modal/', include('apps.modal.urls', namespace='modal')),
    url(r'^', include('apps.shop.urls', namespace='shop')),
]

# configuration for serve media files in local
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/polls/models.py
import uuid
from django.db import models


class Poll(models.Model):
	id = models.UUIDField(
		primary_key=True, 
		default=uuid.uuid4, 
		editable=False
	)
	name = models.CharField(
		max_length=30
	)

	def __str__(self):
		return '%s' % self.name

apps/polls/views.py
from django.views.generic import CreateView, ListView, DetailView
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse
from .models import Poll


class PollCreateView(CreateView):
    model = Poll
    fields = ('name',)

    def get_success_url(self):
        return reverse('polls:list')


class PollListView(ListView):
    model = Poll
    fields = ('name',)
    template_name = 'polls/poll_list.html'


class PollDetailView(DetailView):
    model = Poll


class SearchRedirectView(RedirectView):
  url = 'https://google.com/?q=%(term)s'

apps/polls/templates/polls/poll_detail.html
{{object}}

apps/polls/templates/polls/poll_form.html
<h1>Este es el create</h1>

<form class="form-horizontal" autocomplete="off" method="post" role="form">
	{% csrf_token %}
	{% for field in form %}
	    {% if not field.is_hidden %}
	        <div class="form-group">
	            <label class="col-sm-2 control-label">
	                {{ field.label }}
	                {% if field.field.required %}
	                    <b style="color: red;">*</b>
	                {% endif %}
	            </label>
	            <div class="col-xs-4 col-md-{{ medidaInput }}">
	                {{ field }}
	            </div>
	            <div>
	                  {{ field.help_text }}
	            </div>

	            <div class="col-sm-offset-5 col-sm-7">
	                <input type="submit" value="Crear" class="btn btn-success">
	            </div>

	        </div>
	    {% else %}
	        {{ field }}
	    {% endif %}
	{% endfor %}
</form>

apps/polls/templates/polls/poll_list.html
<h1>Esta es la lista</h1>

<ul>
	{% for object in object_list %}

		<li>{{ object }}</li> 
		<a href="{% url 'polls:detail' object.pk %}">Detail</a>

	{% empty %}

		<h2>Sin registros</h2>

	{% endfor %}
</ul>