apps/modal/urls.py
from django.conf.urls import url
from .views import (
    ListadoProveedores,
    CrearProveedor,
    ModificarProveedor,
    DetalleProveedor,
)


urlpatterns = [
    url(r'^proveedores/$', ListadoProveedores.as_view(), name="listado_proveedores"),
    url(r'^crear_proveedor/$', CrearProveedor.as_view(), name="crear_proveedor"),
    url(r'^modificar_proveedor/(?P<pk>.+)/$',ModificarProveedor.as_view(), name="modificar_proveedor"),
    url(r'^detalle_proveedor/(?P<pk>.+)/$',DetalleProveedor.as_view(), name="detalle_proveedor"),
]

oneeleven/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^caronte/', admin.site.urls),
    url(r'^polls/', include('apps.polls.urls', namespace='polls')),
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^orders/', include('apps.orders.urls', namespace='orders')),
    url(r'^modal/', include('apps.modal.urls', namespace='modal')),
    url(r'^', include('apps.shop.urls', namespace='shop')),
]

# configuration for serve media files in local
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/modal/models.py
from django.db import models


class Proveedor(models.Model):
    ruc = models.CharField(unique=True,max_length=11)
    razon_social = models.CharField(max_length=150)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=15,null=True)
    correo = models.EmailField(null=True)
    estado = models.BooleanField(default=True)

apps/modal/forms.py
from django import forms
from .models import Proveedor


class ProveedorForm(forms.ModelForm):

    class Meta:
        model = Proveedor
        fields = [
            'ruc', 
            'razon_social', 
            'direccion', 
            'telefono',
            'correo', 
            'estado',
        ]

    def __init__(self, *args, **kwargs):
        super(ProveedorForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            if field != 'estado':
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })

apps/modal/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, 
    ListView, 
    DetailView,
    UpdateView,
)
from .forms import ProveedorForm
from .models import Proveedor


class ListadoProveedores(ListView):
    model = Proveedor
    template_name = 'modal/proveedores.html'
    context_object_name = 'proveedores'


class CrearProveedor(CreateView):
    template_name = 'modal/form.html'
    form_class = ProveedorForm
    success_url = reverse_lazy('modal:listado_proveedores')


class ModificarProveedor(UpdateView):
    model = Proveedor
    template_name = 'modal/form.html'
    form_class = ProveedorForm
    success_url = reverse_lazy('modal:listado_proveedores')


class DetalleProveedor(DetailView):
    model = Proveedor
    template_name = 'modal/detalle_proveedor.html'

apps/modal/templates/modal/detalle_proveedor.html
<div class="modal-dialog modal-lg">
        <div class="modal-content">
                <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">x</button>
                        <h3>Detalle Proveedor</h3>
                </div>
                <div class="modal-body">
                        <div class="row">
                                <div class="col-lg-4">
                                        <label>RUC:</label>
                                        <p>{{ object.ruc }}</p>
                                        <label>RAZÓN SOCIAL:</label>
                                        <p>{{ object.razon_social }}</p>
                                        <label>DIRECCIÓN:</label>
                                        <p>{{ object.direccion }}</p>
                                        <label>TELÉFONO:</label>
                                        <p>{{ object.telefono }}</p>
                                        <label>CORREO:</label>
                                        <p>{{ object.correo }}</p>
                                        <label>ESTADO:</label>
                                        {% if object.estado %}
                                                <p>ACTIVO</p>
                                        {% else %}
                                                <p>INACTIVO</p>
                                        {% endif %}
                                </div>
                        </div>
                </div>
                <div class="modal-footer">
                        <div class="col-lg-12 text-right">
                                <button type="button" class="btn btn-primary" onclick="return cerrar_modal()">
                                        Aceptar
                                </button>
                        </div>
                </div>
        </div>
</div>

apps/modal/templates/modal/form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if object %}
            <form role="form" action="{% url 'modal:modificar_proveedor' object.pk %}" method="post">
        {% else %}
            <form role="form" action="{% url 'modal:crear_proveedor' %}" method="post">
        {% endif %}
		        <div class="modal-header">
		            <button type="button" class="close" data-dismiss="modal">x</button>
		            <h3>Modificar Proveedor</h3>
		        </div>
		        <div class="modal-body">
		            {% csrf_token %}
		            <div class="panel panel-default">
		                <div class="panel-body">
		                    {{ form.as_p }}
		                </div>
		            </div>
		        </div>
		        <div class="modal-footer">
		            <div class="col-lg-12 text-right">
		                <input type="submit" class="btn btn-primary" name="submit" value="Guardar">
		                <button type="button" class="btn btn-default" onclick="return cerrar_modal()">Cancelar</button>
		            </div>
		        </div>
        	</form>
    </div>
</div>

apps/modal/templates/modal/proveedores.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Proveedores{% endblock %}
{% block content %}
	<div class="row">
        <div class="col-lg-10">
            <a onclick="return abrir_modal('{% url 'modal:crear_proveedor' %}')" class="btn btn-primary">Crear</a>
        </div>
	</div>
	<hr/>
	<div class="row">
        <div class="col-lg-12">
            <table id="tabla" class="display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th class="text-center">RUC</th>
                        <th class="text-center">RAZON SOCIAL</th>
                        <th class="text-center">DIRECCION</th>
                        <th class="text-center">ESTADO</th>
                        <th class="text-center">ACCIONES</th>
                    </tr>
                </thead>
                <tbody>
                    {% for proveedor in proveedores %}
	                	<tr>
		                    <td>{{ proveedor.ruc }}</td>
		                    <td>{{ proveedor.razon_social }}</td>
		                    <td>{{ proveedor.direccion }}</td>
                    		{% if proveedor.estado %}
                    			<td>ACTIVO</td>
                    		{% else %}
                    			<td>INACTIVO</td>
                    		{% endif %}
		                    <td class="text-center">
		                        <a onclick="return abrir_modal('{% url 'modal:detalle_proveedor' proveedor.pk %}')" class="btn">detail
		                            <span class="glyphicon glyphicon-eye-open"></span>
		                        </a>
		                        <a onclick="return abrir_modal('{% url 'modal:modificar_proveedor' proveedor.pk %}')" class="btn">modify
		                            <span class="glyphicon glyphicon-edit"></span>
		                        </a>
		                    </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
	</div>
	<div id="popup" class="modal fade" role="dialog"> </div>
	<script type="text/javascript">
		function abrir_modal(url)
			{
			        $('#popup').load(url, function()
			        {
			                $(this).modal('show');
			        });
			        return false;
			}
		function cerrar_modal()
			{
			        $('#popup').modal('hide');
			        return false;
			}
	</script>
{% endblock %}